import { NextResponse } from "next/server";
import { getRequestIdentity } from "@/lib/auth";
import { createWorkflow } from "@/lib/db/workflows";
import { getOptionalEnv } from "@/lib/env";
import type { WorkflowEdge, WorkflowNode } from "@/types/workflow";

type DraftPayload = {
  workflowName?: string;
  explanation?: string;
  nodes?: WorkflowNode[];
  edges?: WorkflowEdge[];
};

function databaseConfigured() {
  return Boolean(getOptionalEnv("NEXT_PUBLIC_SUPABASE_URL") && getOptionalEnv("SUPABASE_SERVICE_ROLE_KEY"));
}

export async function POST(request: Request) {
  try {
    if (!databaseConfigured()) {
      return NextResponse.json(
        { error: "Supabase is not configured. Draft workflow creation is disabled in demo mode." },
        { status: 503 }
      );
    }

    const identity = await getRequestIdentity();
    const body = (await request.json()) as DraftPayload;

    if (!body.workflowName?.trim()) {
      return NextResponse.json({ error: "Workflow name is required." }, { status: 400 });
    }

    const workflow = await createWorkflow({
      ownerId: identity.userId,
      name: body.workflowName.trim(),
      description: body.explanation ?? "Draft workflow generated by Rovanta AI.",
      status: "draft",
      nodes: body.nodes ?? [],
      edges: body.edges ?? []
    });

    return NextResponse.json({ id: workflow.id, status: workflow.status });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Unable to create draft workflow." },
      { status: 500 }
    );
  }
}
